root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/."

bin = "./tmp/main"

include_ext = ["go", "tpl", "tmpl", "html"]

exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]

exclude_regex = ["_test\\.go"]

polling = true
polling_interval = 500

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
